apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Calico API Server (Requires manual creation of the cert secret)
  - https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/apiserver.yaml
  - resources/gnp-base.yaml
  - resources/gnp-istio.yaml
  - resources/gnp-clusterip.yaml
  # Finish with HostEndpoints as they will trigger policy enforcement.
  - resources/hosts.yaml
  # Apply FelixConfiguration -> Remove Failsafes.
  - resources/felixconfig.yaml