apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adguard.name" . }}
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adguard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adguard.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "adguard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-config
        image: busybox
        envFrom:
          - secretRef:
              name: adguard-admin-password
        command: ['sh', '-c', "awk -v H=\"$ADGUARD_ADMIN_PASSWORD_HASH\" '{gsub(/<adguard-admin-password>/, H); print}' /config/AdGuardHome.yaml > /mnt/AdGuardHome.yaml && chmod 0666 /mnt/AdGuardHome.yaml"]
        volumeMounts:
          - name: config-source
            mountPath: /config
          - name: config
            mountPath: /mnt
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /opt/adguardhome/conf
          - name: data
            mountPath: /opt/adguardhome/work
      volumes:
        - name: config-source
          configMap:
            name: adguard-config
        - name: config
          emptyDir:
            medium: Memory
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.storage.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
