# Simple service to test routing.
services:
  otelcol:
    image: docker.io/otel/opentelemetry-collector
    networks: 
      - traefik
    volumes:
      - ./otel.yaml:/etc/otelcol/config.yaml:ro
    ports:
      # - 1888:1888 # pprof extension
      # - 8880:8888 # Prometheus metrics exposed by the Collector
      # - 8889:8889 # Prometheus exporter metrics
      # - 13133:13133 # health_check extension
      # - 4317:4317 # OTLP gRPC receiver
      # - 4318:4318 # OTLP http receiver
      # - 55679:55679 # zpages extension


networks:
  traefik:
    name: traefik