apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-http
spec:
  ingress:
  - from:
    ports:
      - port: 8096
        protocol: TCP
  podSelector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress