# openebs/openebs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: openebs
    repoURL: https://openebs.github.io/charts
    targetRevision: 3.10.0
    # helm:
    #   valuesObject:
    #     key: value
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
---
# openebs-nfs/nfs-provisioner
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-nfs-provisioner
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-provisioner
    repoURL: https://openebs.github.io/dynamic-nfs-provisioner
    targetRevision: 0.11.0
    helm:
      parameters:
      - name: "nfsStorageClass.backendStorageClass"
        value: "zfs-rwo"
      - name: "nfsStorageClass.name"
        value: "zfs-rwx"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs

