---
    - name: Install virtualization packages
      pacman:
        name: qemu,ovmf,dnsmasq,libvirt

    # ip forwarding
    - name: Enable IP forwarding.
      copy:
        src: files/30-forward.conf
        dest: /etc/sysctl.d/30-forward.conf
        owner: root
        group: root
        mode: 0644
    # dnsmasq
    - name: Configure dnsmasq
      block:
        - copy:
            src:  files/dnsmasq/
            dest: /var/lib/dnsmasq
          name: Configure dnsmasq

        - copy:
            src: files/qemu0/
            dest: /usr/lib/systemd/network
          name: Configure network bridge
          notify:
            - restart networkd

        - name: Create hosts file
          file:
            path: /var/lib/dnsmasq/qemu0.hosts
            state: touch

        - copy:
            src: files/dnsmasq@.service
            dest: /usr/lib/systemd/system/dnsmasq@.service
          name: Enable dnsmasq
          notify:
            - restart dnsmasq

        - name: Configure OVMF
          lineinfile:
            path: /etc/libvirt/qemu.conf
            regexp: '^nvram'
            insertbefore: '^#nvram'
            line: 'nvram = [ "/usr/share/ovmf/x64/OVMF_CODE.fd:/usr/share/ovmf/x64/OVMF_VARS.fd" ]'

        - name: Enable dnsmasq
          service:
            name: dnsmasq@qemu0
            enabled: true
            state: started

    - name: Configure services
      block:
        - service:
            name: libvirtd
            enabled: true
            state: started
          name: Enable libvirtd

        - service:
            name: virtlogd
            enabled: true
            state: started
          name: Enable virtlogd

        - service:
            name: systemd-networkd
            enabled: true
            state: started
          name: Enable networkd

