# https://docs.tigera.io/calico/latest/reference/resources/felixconfig
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfConnectTimeLoadBalancing: TCP
  bpfHostNetworkedNATWithoutCTLB: Enabled
  bpfLogLevel: ""
  floatingIPs: Disabled
  logSeverityScreen: Info
  reportingInterval: 0s
  # Restricted failsafe ports for startup and recovery.
  failsafeInboundHostPorts: [6443] # Always allow kube-api for controllers
  failsafeOutboundHostPorts: [53, 67] # Always allow DNS and DHCP