metrics:
  addInternals: true
  otlp:
    grpc:
      endpoint: otelcol:4317
      tls:
        insecureskipverify: true
# Traces
tracing:
  otlp:
    grpc:
      endpoint: otelcol:4317
      tls:
        insecureskipverify: true
# Logging
experimental:
  otlpLogs: true
log:
  level: WARN
  otlp:
    grpc:
      endpoint: otelcol:4317
      tls:
        insecureskipverify: true
accessLog:
  # dualOutput: false
  otlp:
    grpc:
      endpoint: otelcol:4317
      tls:
        insecureskipverify: true

api:
  insecure: true
  dashboard: true
entrypoints:
  web:
    address: :80

providers:
  docker: true