# https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    # Add this finalizer ONLY if you want these to cascade delete.
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: root
spec:
  project: default
  source:
    # Can point to either a Helm chart repo or a git repo.
    repoURL: https://github.com/alxbl/lab.git
    # For Helm, this refers to the chart version.
    targetRevision: HEAD  
    # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
    path: infra/k8s/argocd/apps

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Extra information to show in the Argo CD Application details tab
  info:
    - name: 'Description:'
      value: 'Meta-application which deploys all cluster applications'
