# https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-catalog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: system-catalog
spec:
  project: system
  source:
    repoURL: https://github.com/alxbl/lab.git
    targetRevision: HEAD  
    path: infra/system/catalog

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  info:
    - name: 'Description:'
      value: 'Meta-application for cluster system applications'
