# Certificate for HTTP(s) ingress (https://cert-manager.io/docs/usage/certificate/#creating-certificate-resources)
# Issued by Let's Encrypt
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https-in-gw-cert
  namespace: istio-ingress
spec:
  secretName: https-in-gw-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - segfault.me
  # The use of the common name field has been deprecated since 2000 and is discouraged.
  # commonName: segfault.me
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  usages:
    - server auth
    - client auth
  dnsNames:
    - segfault.me
    - www.segfault.me 
    - lab.segfault.me
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
    group: cert-manager.io