# Deny anything that doesn't match an explicit allow rule.
# ref: https://istio.io/latest/docs/reference/config/security/authorization-policy/
# ref: https://www.tenable.com/policies/cloud-security/AC_K8S_0121
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ingress-allow-nothing
  namespace: istio-system
spec:
  action: ALLOW
---
# Allow all HTTP(S) to flow through ingress
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ingress-allow-https
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts: ["*.segfault.me"]
        ports: ["80", "443"]
---
# Allow SMB to flow through ingress
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ingress-allow-smbd
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: ["445"]