# https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: root
spec:
  project: default
  source:
    repoURL: https://github.com/alxbl/lab.git
    targetRevision: HEAD  
    path: infra/k8s/catalog
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  info:
    - name: 'Description:'
      value: 'Meta-application which deploys cluster applications'
