apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-smb
spec:
  ingress:
  - from:
    ports:
      - port: 445
        protocol: TCP
  podSelector:
    matchLabels:
      {{- include "smbd.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
