# Cloudflare API token with: segfault.me - DNS:Edit, Zone:Read
# ref: https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-secret
  namespace: cert-manager
type: Opaque
data:
  api-token: REDACTED
