# Cloudflare API token with: segfault.me - DNS:Edit, Zone:Read
# ref: https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-admin-creds
  namespace: postgres
type: Opaque
stringData:
  admin-password: REDACTED
  user-password: REDACTED
  replication-password: REDACTED
