# https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/backupstoragelocation.md
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: azure
  namespace: system
spec:
  provider: velero.io/azure
  objectStorage:
    bucket: velero 
    prefix: ''
  config:
    storageAccount: REDACTED
    storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
    storageAccountURI: https://REDACTED.blob.core.windows.net/
    useAAD: "true"
    activeDirectoryAuthorityURI: https://login.microsoftonline.us/
    blockSizeInBytes: "1048576"