apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- overlays/helm-repositories.yaml 
- overlays/namespace.yaml
- overlays/root.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.6/manifests/install.yaml
patches:
- path: overlays/argocd-server.yaml
# FIXME: Patch redis to not inject istio (usersecret-init)