apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- overlays/helm-repositories.yaml 
- overlays/namespace.yaml
- overlays/aoa-root.yaml
- overlays/aoa-system.yaml
- projects/argoproj-system.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.5.2/manifests/install.yaml
patches:
- path: overlays/argocd-server.yaml
# FIXME: Patch redis to not inject istio (usersecret-init) 
#        Alternatively: (https://github.com/istio/istio/discussions/52841)