apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: system
  source:
    path: infra/system/olm
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: olm
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
  labels:
    istio-injection: disabled