# Certificate issuer for external services.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: admin@segfault.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        cloudflare:
          email: admin@segfault.com
          apiTokenSecretRef:
            name: cloudflare-api-secret
            key: api-token
      selector:
        dnsZones:
          - segfault.me