apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Allow CalicoPolicy integration with Istio
  # - https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/csi-driver.yaml
  # - https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/alp/istio-app-layer-policy-envoy-v3.yaml

  - manifests/namespaces.yaml
  - manifests/charts.yaml
  - manifests/certificate.yaml
  - manifests/gateway.yaml
  - manifests/service.yaml
  - manifests/mtls.yaml
  - manifests/policies.yaml
  
  - services/argocd.yaml
