apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespaces.yaml
  - manifests/charts.yaml
  - manifests/certificate.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
