apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satisfactory.fullname" . }}
  labels:
    {{- include "satisfactory.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "satisfactory.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "satisfactory.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "satisfactory.serviceAccountName" . }}
      {{- if not .Values.service.create }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ROOTLESS
              value: "false"
            - name: STEAMBETA
              value: "false"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: MAXPLAYERS
              value: {{ .Values.config.maxPlayers | quote }} 
          ports:
            - name: beacon
              containerPort: 15000
              protocol: UDP
            - name: discovery
              containerPort: 15777
              protocol: UDP
            - name: game
              containerPort: 7777
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: satisfactory-data
              mountPath: /config/
            - name: gamefiles
              mountPath: /config/gamefiles
      volumes:
        - name: satisfactory-data
          persistentVolumeClaim:
            claimName: {{ .Values.storage.name | quote }}
        - name: gamefiles
          emptyDir:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
