apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-satisfactory
  namespace: satisfactory
spec:
  ingress:
  - from:
    ports:
      - port: 15000
        protocol: UDP
      - port: 15777
        protocol: UDP
      - port: 7777
        protocol: UDP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: satisfactory
  policyTypes:
  - Ingress
