{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "satisfactory.fullname" . }}
  labels:
    {{- include "satisfactory.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: 10.3.44.44
  ports:
    - port: 7777
      targetPort: 7777
      protocol: UDP
      name: game
    - port: 15000
      targetPort: 15000
      protocol: UDP
      name: discovery
    - port: 15777
      targetPort: 15777
      protocol: UDP
      name: beacon
  selector:
    {{- include "satisfactory.selectorLabels" . | nindent 4 }}
{{- end }}