apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-satisfactory
  namespace: satisfactory
spec:
  ingress:
  - from:
    ports:
      - port: 15000
        protocol: UDP
      - port: 15777
        protocol: UDP
      - port: 7777
        protocol: UDP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: satisfactory
  policyTypes:
  - Ingress
---
# FIXME: This is necessary until Satisfactory is no longer exposed on host network.
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: host-allow-satisfactory
spec:
  selector: "type == 'endpoint'"
  ingress:
    - action: Allow
      protocol: UDP
      destination:
        ports: [7777, 15000, 15777]
