#!/usr/bin/env bash
# USAGE: ./scripts/get-fedora-coreos
# USAGE: ./scripts/get-fedora-coreos stream version dest
#
# Adapted from: https://github.com/poseidon/matchbox/blob/main/scripts/get-fedora-coreos
set -eou pipefail

STREAM=${1:-"stable"}
DEST_DIR=${3:-"$PWD/../build/bootstrap/matchbox/assets"}
DEST=$DEST_DIR/fedora-coreos
ARCH=${4:-"x86_64"}

JSON=$(curl "https://builds.coreos.fedoraproject.org/streams/$STREAM.json") # FIXME: Error handling

if [[ -z "$JSON" ]]; then
  echo "Release Stream not found"
  exit 1
fi

VERSION_LATEST=$(echo $JSON | jq -r ".architectures.$ARCH.artifacts.metal.release")
VERSION=${2:-"$VERSION_LATEST"}


BASE_URL=https://builds.coreos.fedoraproject.org/prod/streams/$STREAM/builds/$VERSION/$ARCH
# check stream/version exist based on the header response
if ! curl -s -I $BASE_URL/fedora-coreos-$VERSION-metal.$ARCH.raw.xz | grep -q -E '^HTTP/[0-9.]+ [23][0-9][0-9]' ; then
  echo "Release version not found"
  exit 1
fi

if [ ! -d "$DEST" ]; then
  echo "Creating directory $DEST"
  mkdir -p $DEST
fi

echo "Downloading Fedora CoreOS $STREAM $VERSION images to $DEST"

 KERNEL=$(echo $JSON | jq -r ".architectures.$ARCH.artifacts.metal.formats.pxe.kernel.location")
 INITRAMFS=$(echo $JSON | jq -r ".architectures.$ARCH.artifacts.metal.formats.pxe.initramfs.location")
 ROOTFS=$(echo $JSON | jq -r ".architectures.$ARCH.artifacts.metal.formats.pxe.rootfs.location")


# kernel
echo "fedora-coreos-$VERSION-live-kernel.$ARCH"
curl -# "$KERNEL" -o $DEST/fedora-coreos-$VERSION-live-kernel.$ARCH

# initramfs
echo "fedora-coreos-$VERSION-live-initramfs.$ARCH.img"
curl -# "$INITRAMFS" -o $DEST/fedora-coreos-$VERSION-live-initramfs.$ARCH.img

# rootfs
echo "fedora-coreos-$VERSION-live-rootfs.$ARCH.img"
curl -# "$ROOTFS" -o $DEST/fedora-coreos-$VERSION-live-rootfs.$ARCH.img
