apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/gnp-base.yaml
  - resources/gnp-istio.yaml
  - resources/gnp-clusterip.yaml
  - resources/bgpconfig.yaml
  # - resources/controllerconfig.yaml
  # Finish with HostEndpoints as they will trigger policy enforcement.
  - resources/hosts.yaml
  # Apply FelixConfiguration -> Remove Failsafes.
  - resources/felixconfig.yaml
  - https://raw.githubusercontent.com/projectcalico/calico/refs/heads/release-v3.32/manifests/v3_projectcalico_org.yaml