# It feels dirty to have this as part of a different application deployment,
# but the services depend on Istio being present, so for now this is fine.

# ArgoCD virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-svc
  namespace: argocd
spec:
  hosts:
  - "lab.segfault.me"
  gateways:
  - istio-ingress/https-in-gw
  http:
  - match:
    - uri:
        prefix: /argocd
    route:
    - destination:
        port:
          number: 443
        host: argocd-server.argocd.svc.cluster.local
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: argocd-allow-internal
  namespace: argocd
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["argocd"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-non-mtls
  namespace: argocd
spec:
  action: DENY
  rules:
  - from:
    - source:
        notPrincipals: ["*"]