{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "photoprism.name" . }}
  labels:
    {{- include "photoprism.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.settings.HttpPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "photoprism.selectorLabels" . | nindent 4 }}
{{- end }}