apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-app
  namespace: argocd
spec:
  project: default
  source:
    chart: immich
    repoURL: oci://ghcr.io/immich-app/immich-charts/immich
    targetRevision: 0.13.2
    helm:
      valuesObject:
        immich:
          metrics:
            enabled: false  # No ServiceMonitor deployed.
          persistence:
            library:
              existingClaim: immich
          existingConfiguration: immich-cm
          configurationKind: ConfigMap
  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich
  