apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: media
  project: default
  source:
    helm:
      valuesObject:
        storage:
          photos:
            create: false
            name: smbd-data
          database:
            create: true
            size: 5Gi
        settings:
          DatabaseDriver: 'mysql'
    path: infra/k8s/smbd
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
