apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  labels:
    istio-injection: enabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
      
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.2.4
    helm:
      valuesObject:
        # https://github.com/bitnami/charts/tree/main/bitnami/postgresql#postgresql-primary-parameters
        auth:
          existingSecret: postgresql-admin-creds
          username: user
          secretKeys:
            adminPasswordKey: admin-password
            userPasswordKey:  user-password
            replicationPasswordKey: replication-password
        architecture: 'standalone'
        audit:
          logHostname: false
          logConnection: false
           
        primary:
          name: primary

          service:
            type: ClusterIP
            ports:
              postgresql: 5432
            
          persistence:
            enabled: true
            volumeName: postgres-data
            storageClass: "zfs-rwo"
            accessModes: [ReadWriteOnce]
            size: 8Gi
          # persistentVolumeClaimRetentionPolicy: false

          networkPolicy:
            allowExternal: true
            allowExternalEgress: true
            # extraIngress: []
            # extraEgress: []
          resources: {}
          podSecurityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            privileged: false

        serviceAccount:
          name: "postgres-sa"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres