apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    istio-injection: enabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smbd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: media
  project: default
  source:
    helm:
      valuesObject:
        storage:
          create: true
          size: 1Ti
          storageClass: 'zfs-rwx'
          accessMode: ReadWriteMany
    path: infra/k8s/smbd
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
