apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: home
  project: default
  source:
    helm:
      valuesObject:
        storage:
          create: true
          size: 5Gi
          storageClass: 'zfs-rwo'
          accessMode: ReadWriteOnce
    path: infra/home/vaultwarden
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
