apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwifthub
  namespace: default
  labels:
    app: zwifthub
    app.kubernetes.io/name: zwifthub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zwifthub
  template:
    metadata:
      labels:
        app: zwifthub
        app.kubernetes.io/name: zwifthub
    spec:
      containers:
      - name: zwifthub
        image: segvcr.azurecr.io/zwifthub:0.7
        env:
        - name: INTERVALS__INTERVALSAPIKEY
          valueFrom:
            secretKeyRef:
              name: intervals-creds
              key: api_key
              optional: false
        volumeMounts:
        # Override the appsettings with the real settings.
        - name: zwifthub-appsettings
          mountPath: "/app/appsettings.json"
          subPath: "appsettings.json"
          readOnly: true
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: segvcr-auth
      volumes:
        - name: zwifthub-appsettings
          configMap:
            name: zwifthub-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zwifthub-config
  namespace: default
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information"
        },
        "Console": {
          "LogLevel": {
            "Default": "Information"
          }
        }
      },
      "Kestrel": {
        "Endpoints": {
          "http": {
            "Url": "http://0.0.0.0:5000"
          }
        }
      },
      "AllowedHosts": "*",
      "Intervals": {
        "IntervalsApiKey": "",
        "IntervalsUserId": "i87685",
        "PublishFrequency": 1000,
        "MonitorRecentDays": 7,
        "PollInterval": 10000
      },
      "Goals": {
        "DistanceInMeters": 20000000.00,
        "WeightInKg": 68.00,
        "FtpInWatt": 280,
        "Start": "2023-01-01",
        "End": "2023-12-31"
      },
      "Zwift": {
        "SauceEndpoint": "ws://s4z:1080",
        "Uid": 42,
        "ActivityEndedThreshold": 5000
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: zwifthub
spec:
  selector:
    app.kubernetes.io/name: zwifthub
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zwifthub-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-prefixstrip@kubernetescrd
  labels:
    app.kubernetes.io/name: zwifthub
spec:
  rules:
  - http:
      paths:
      - path: /zwift
        pathType: Prefix
        backend:
          service:
            name: zwifthub
            port:
              number: 5000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prefixstrip
spec:
  stripPrefix:
    prefixes:
      - /zwift
  forceSlash: true
